version: '3.8'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tnpothole
      MYSQL_USER: newuser
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: newuser
      PMA_PASSWORD: root
    ports:
      - "8080:80"  # Map phpMyAdmin to a different port to avoid conflicts
    depends_on:
      - db
