version: '3.1'

services:
  php:
    image: php:8.0-apache
    container_name: php-container
    volumes:
      - . /var/www/html/
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: tnpothole
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"
