version: '3.8'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: tnpothole
    ports:
      - "3306:3306"

  app:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
